version: "3.9"

services:
  db:
    image: postgres:15
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saif
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: notes_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:saif@db:5432/notes_db
      GROQ_API_KEY: ${GROQ_API_KEY}
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data: